#pragma once

// custom font header for an icon font created from blender icons
// Creative Commons Attribution-ShareAlike 4.0
// original: https://devtalk.blender.org/t/new-icons-for-blender-2-8x/4651
// split into SVGs: https://github.com/Shrinks99/blender-icons
// use service like https://icomoon.io/app/ to merge into TTF
// overview: https://wilkinson.graphics/blender-icons/
//
// codepoint to hex C:
//
// void codepointToHex(uint32_t codepoint, uint8_t pOutBytes[3])
// {
//     pOutBytes[0] = 0b11100000 | (0x0F & (uint8_t)(codepoint >> 12));
//     pOutBytes[1] = 0b10000000 | (0x3F & (uint8_t)(codepoint >> 6));
//     pOutBytes[2] = 0b10000000 | (0x3F & (uint8_t)codepoint);
// }
//
// codepoint to hex JS:
//
// function codepointToEscapedHex(codepoint) {
//    return "\\x" + Number(224 | (0x0F & (codepoint >> 12))).toString(16) + "\\x"
//       + Number(128 | (0x3F & (codepoint >> 6))).toString(16) + "\\x"
//       + Number(128 | (0x3F & (codepoint))).toString(16);
// }
//

// glyph range for font creation
#define ICON_MIN_BD 0xe900
#define ICON_MAX_BD 0xeb99

#define ICON_BD_ACTION "\xee\xa4\x80"                        // U+e900
#define ICON_BD_ACTION_TWEAK "\xee\xa4\x81"                  // U+e901
#define ICON_BD_ADD "\xee\xa4\x82"                           // U+e902
#define ICON_BD_ALIASED "\xee\xa4\x83"                       // U+e903
#define ICON_BD_ALIGN_BOTTOM "\xee\xa4\x84"                  // U+e904
#define ICON_BD_ALIGN_CENTER "\xee\xa4\x85"                  // U+e905
#define ICON_BD_ALIGN_FLUSH "\xee\xa4\x86"                   // U+e906
#define ICON_BD_ALIGN_JUSTIFY "\xee\xa4\x87"                 // U+e907
#define ICON_BD_ALIGN_LEFT "\xee\xa4\x88"                    // U+e908
#define ICON_BD_ALIGN_MIDDLE "\xee\xa4\x89"                  // U+e909
#define ICON_BD_ALIGN_RIGHT "\xee\xa4\x8a"                   // U+e90a
#define ICON_BD_ALIGN_TOP "\xee\xa4\x8b"                     // U+e90b
#define ICON_BD_ANCHOR_BOTTOM "\xee\xa4\x8c"                 // U+e90c
#define ICON_BD_ANCHOR_CENTER "\xee\xa4\x8d"                 // U+e90d
#define ICON_BD_ANCHOR_LEFT "\xee\xa4\x8e"                   // U+e90e
#define ICON_BD_ANCHOR_RIGHT "\xee\xa4\x8f"                  // U+e90f
#define ICON_BD_ANCHOR_TOP "\xee\xa4\x90"                    // U+e910
#define ICON_BD_ANIM "\xee\xa4\x91"                          // U+e911
#define ICON_BD_ANIM_DATA "\xee\xa4\x92"                     // U+e912
#define ICON_BD_ANTIALIASED "\xee\xa4\x93"                   // U+e913
#define ICON_BD_APPEND_BLEND "\xee\xa4\x94"                  // U+e914
#define ICON_BD_ARMATURE_DATA "\xee\xa4\x95"                 // U+e915
#define ICON_BD_ARROW_LEFTRIGHT "\xee\xa4\x96"               // U+e916
#define ICON_BD_ASSET_MANAGER "\xee\xa4\x97"                 // U+e917
#define ICON_BD_AUTO "\xee\xa4\x98"                          // U+e918
#define ICON_BD_AUTOMERGE_OFF "\xee\xa4\x99"                 // U+e919
#define ICON_BD_AUTOMERGE_ON "\xee\xa4\x9a"                  // U+e91a
#define ICON_BD_AXIS_FRONT "\xee\xa4\x9b"                    // U+e91b
#define ICON_BD_AXIS_SIDE "\xee\xa4\x9c"                     // U+e91c
#define ICON_BD_AXIS_TOP "\xee\xa4\x9d"                      // U+e91d
#define ICON_BD_BACK "\xee\xa4\x9e"                          // U+e91e
#define ICON_BD_BLENDER "\xee\xa4\x9f"                       // U+e91f
#define ICON_BD_BOIDS "\xee\xa4\xa0"                         // U+e920
#define ICON_BD_BOLD "\xee\xa4\xa1"                          // U+e921
#define ICON_BD_BONE_DATA "\xee\xa4\xa2"                     // U+e922
#define ICON_BD_BOOKMARKS "\xee\xa4\xa3"                     // U+e923
#define ICON_BD_BORDERMOVE "\xee\xa4\xa4"                    // U+e924
#define ICON_BD_BRUSH_DATA "\xee\xa4\xa5"                    // U+e925
#define ICON_BD_BRUSHES_ALL "\xee\xa4\xa6"                   // U+e926
#define ICON_BD_CAMERA_DATA "\xee\xa4\xa7"                   // U+e927
#define ICON_BD_CAMERA_STEREO "\xee\xa4\xa8"                 // U+e928
#define ICON_BD_CANCEL "\xee\xa4\xa9"                        // U+e929
#define ICON_BD_CENTER_ONLY "\xee\xa4\xaa"                   // U+e92a
#define ICON_BD_CHECKBOX_DEHLT "\xee\xa4\xab"                // U+e92b
#define ICON_BD_CHECKBOX_HLT "\xee\xa4\xac"                  // U+e92c
#define ICON_BD_CHECKMARK "\xee\xa4\xad"                     // U+e92d
#define ICON_BD_CLIP_UV_DEHLT "\xee\xa4\xae"                 // U+e92e
#define ICON_BD_CLIP_UV_HLT "\xee\xa4\xaf"                   // U+e92f
#define ICON_BD_COLLAPSEMENU "\xee\xa4\xb0"                  // U+e930
#define ICON_BD_COLLECTION_NEW "\xee\xa4\xb1"                // U+e931
#define ICON_BD_COLOR "\xee\xa4\xb2"                         // U+e932
#define ICON_BD_COLOR_ALPHA "\xee\xa4\xb3"                   // U+e933
#define ICON_BD_COLOR_BLUE "\xee\xa4\xb4"                    // U+e934
#define ICON_BD_COLOR_GREEN "\xee\xa4\xb5"                   // U+e935
#define ICON_BD_COLOR_RED "\xee\xa4\xb6"                     // U+e936
#define ICON_BD_COMMUNITY "\xee\xa4\xb7"                     // U+e937
#define ICON_BD_CON_ACTION "\xee\xa4\xb8"                    // U+e938
#define ICON_BD_CON_ARMATURE "\xee\xa4\xb9"                  // U+e939
#define ICON_BD_CON_CAMERASOLVER "\xee\xa4\xba"              // U+e93a
#define ICON_BD_CON_CHILDOF "\xee\xa4\xbb"                   // U+e93b
#define ICON_BD_CON_CLAMPTO "\xee\xa4\xbc"                   // U+e93c
#define ICON_BD_CON_DISTLIMIT "\xee\xa4\xbd"                 // U+e93d
#define ICON_BD_CON_FLOOR "\xee\xa4\xbe"                     // U+e93e
#define ICON_BD_CON_FOLLOWPATH "\xee\xa4\xbf"                // U+e93f
#define ICON_BD_CON_FOLLOWTRACK "\xee\xa5\x80"               // U+e940
#define ICON_BD_CON_KINEMATIC "\xee\xa5\x81"                 // U+e941
#define ICON_BD_CON_LOCKTRACK "\xee\xa5\x82"                 // U+e942
#define ICON_BD_CON_LOCLIKE "\xee\xa5\x83"                   // U+e943
#define ICON_BD_CON_LOCLIMIT "\xee\xa5\x84"                  // U+e944
#define ICON_BD_CON_OBJECTSOLVER "\xee\xa5\x85"              // U+e945
#define ICON_BD_CON_PIVOT "\xee\xa5\x86"                     // U+e946
#define ICON_BD_CON_ROTLIKE "\xee\xa5\x87"                   // U+e947
#define ICON_BD_CON_ROTLIMIT "\xee\xa5\x88"                  // U+e948
#define ICON_BD_CON_SAMEVOL "\xee\xa5\x89"                   // U+e949
#define ICON_BD_CON_SHRINKWRAP "\xee\xa5\x8a"                // U+e94a
#define ICON_BD_CON_SIZELIKE "\xee\xa5\x8b"                  // U+e94b
#define ICON_BD_CON_SIZELIMIT "\xee\xa5\x8c"                 // U+e94c
#define ICON_BD_CON_SPLINEIK "\xee\xa5\x8d"                  // U+e94d
#define ICON_BD_CON_STRETCHTO "\xee\xa5\x8e"                 // U+e94e
#define ICON_BD_CON_TRACKTO "\xee\xa5\x8f"                   // U+e94f
#define ICON_BD_CON_TRANSFORM "\xee\xa5\x90"                 // U+e950
#define ICON_BD_CON_TRANSFORM_CACHE "\xee\xa5\x91"           // U+e951
#define ICON_BD_CON_TRANSLIKE "\xee\xa5\x92"                 // U+e952
#define ICON_BD_CONE "\xee\xa5\x93"                          // U+e953
#define ICON_BD_CONSOLE "\xee\xa5\x94"                       // U+e954
#define ICON_BD_CONSTRAINT "\xee\xa5\x95"                    // U+e955
#define ICON_BD_CONSTRAINT_BONE "\xee\xa5\x96"               // U+e956
#define ICON_BD_COPY_DOWN "\xee\xa5\x97"                     // U+e957
#define ICON_BD_COPY_ID "\xee\xa5\x98"                       // U+e958
#define ICON_BD_CUBE "\xee\xa5\x99"                          // U+e959
#define ICON_BD_CURSOR "\xee\xa5\x9a"                        // U+e95a
#define ICON_BD_CURVE_BEZCIRCLE "\xee\xa5\x9b"               // U+e95b
#define ICON_BD_CURVE_BEZCURVE "\xee\xa5\x9c"                // U+e95c
#define ICON_BD_CURVE_DATA "\xee\xa5\x9d"                    // U+e95d
#define ICON_BD_CURVE_NCIRCLE "\xee\xa5\x9e"                 // U+e95e
#define ICON_BD_CURVE_NCURVE "\xee\xa5\x9f"                  // U+e95f
#define ICON_BD_CURVE_PATH "\xee\xa5\xa0"                    // U+e960
#define ICON_BD_DECORATE "\xee\xa5\xa1"                      // U+e961
#define ICON_BD_DECORATE_ANIMATE "\xee\xa5\xa2"              // U+e962
#define ICON_BD_DECORATE_DRIVER "\xee\xa5\xa3"               // U+e963
#define ICON_BD_DECORATE_KEYFRAME "\xee\xa5\xa4"             // U+e964
#define ICON_BD_DECORATE_LIBRARY_OVERRIDE "\xee\xa5\xa5"     // U+e965
#define ICON_BD_DECORATE_LINKED "\xee\xa5\xa6"               // U+e966
#define ICON_BD_DECORATE_LOCKED "\xee\xa5\xa7"               // U+e967
#define ICON_BD_DECORATE_OVERRIDE "\xee\xa5\xa8"             // U+e968
#define ICON_BD_DECORATE_UNLOCKED "\xee\xa5\xa9"             // U+e969
#define ICON_BD_DESKTOP "\xee\xa5\xaa"                       // U+e96a
#define ICON_BD_DISCLOSURE_TRI_DOWN "\xee\xa5\xab"           // U+e96b
#define ICON_BD_DISCLOSURE_TRI_RIGHT "\xee\xa5\xac"          // U+e96c
#define ICON_BD_DISK "\xee\xa5\xad"                          // U+e96d
#define ICON_BD_DISK_DRIVE "\xee\xa5\xae"                    // U+e96e
#define ICON_BD_DOCUMENTS "\xee\xa5\xaf"                     // U+e96f
#define ICON_BD_DOT "\xee\xa5\xb0"                           // U+e970
#define ICON_BD_DOWNARROW_HLT "\xee\xa5\xb1"                 // U+e971
#define ICON_BD_DRIVER "\xee\xa5\xb2"                        // U+e972
#define ICON_BD_DRIVER_DISTANCE "\xee\xa5\xb3"               // U+e973
#define ICON_BD_DRIVER_ROTATIONAL_DIFFERENCE "\xee\xa5\xb4"  // U+e974
#define ICON_BD_DRIVER_TRANSFORM "\xee\xa5\xb5"              // U+e975
#define ICON_BD_DUPLICATE "\xee\xa5\xb6"                     // U+e976
#define ICON_BD_EDGE_SELECT "\xee\xa5\xb7"                   // U+e977
#define ICON_BD_EDITMODE_HLT "\xee\xa5\xb8"                  // U+e978
#define ICON_BD_EMPTY_ARROWS "\xee\xa5\xb9"                  // U+e979
#define ICON_BD_EMPTY_AXIS "\xee\xa5\xba"                    // U+e97a
#define ICON_BD_EMPTY_DATA "\xee\xa5\xbb"                    // U+e97b
#define ICON_BD_EMPTY_SINGLE_ARROW "\xee\xa5\xbc"            // U+e97c
#define ICON_BD_ERROR "\xee\xa5\xbd"                         // U+e97d
#define ICON_BD_EXPERIMENTAL "\xee\xa5\xbe"                  // U+e97e
#define ICON_BD_EXTERNAL_DRIVE "\xee\xa5\xbf"                // U+e97f
#define ICON_BD_EYEDROPPER "\xee\xa6\x80"                    // U+e980
#define ICON_BD_FACE_MAPS "\xee\xa6\x81"                     // U+e981
#define ICON_BD_FACE_SELECT "\xee\xa6\x82"                   // U+e982
#define ICON_BD_FAKE_USER_OFF "\xee\xa6\x83"                 // U+e983
#define ICON_BD_FAKE_USER_ON "\xee\xa6\x84"                  // U+e984
#define ICON_BD_FCURVE "\xee\xa6\x85"                        // U+e985
#define ICON_BD_FCURVE_SNAPSHOT "\xee\xa6\x86"               // U+e986
#define ICON_BD_FF "\xee\xa6\x87"                            // U+e987
#define ICON_BD_FILE "\xee\xa6\x88"                          // U+e988
#define ICON_BD_FILE_3D "\xee\xa6\x89"                       // U+e989
#define ICON_BD_FILE_ARCHIVE "\xee\xa6\x8a"                  // U+e98a
#define ICON_BD_FILE_BACKUP "\xee\xa6\x8b"                   // U+e98b
#define ICON_BD_FILE_BLANK "\xee\xa6\x8c"                    // U+e98c
#define ICON_BD_FILE_BLEND "\xee\xa6\x8d"                    // U+e98d
#define ICON_BD_FILE_CACHE "\xee\xa6\x8e"                    // U+e98e
#define ICON_BD_FILE_FOLDER "\xee\xa6\x8f"                   // U+e98f
#define ICON_BD_FILE_FONT "\xee\xa6\x90"                     // U+e990
#define ICON_BD_FILE_HIDDEN "\xee\xa6\x91"                   // U+e991
#define ICON_BD_FILE_IMAGE "\xee\xa6\x92"                    // U+e992
#define ICON_BD_FILE_MOVIE "\xee\xa6\x93"                    // U+e993
#define ICON_BD_FILE_NEW "\xee\xa6\x94"                      // U+e994
#define ICON_BD_FILE_PARENT "\xee\xa6\x95"                   // U+e995
#define ICON_BD_FILE_REFRESH "\xee\xa6\x96"                  // U+e996
#define ICON_BD_FILE_SCRIPT "\xee\xa6\x97"                   // U+e997
#define ICON_BD_FILE_SOUND "\xee\xa6\x98"                    // U+e998
#define ICON_BD_FILE_TEXT "\xee\xa6\x99"                     // U+e999
#define ICON_BD_FILE_TICK "\xee\xa6\x9a"                     // U+e99a
#define ICON_BD_FILE_VOLUME "\xee\xa6\x9b"                   // U+e99b
#define ICON_BD_FILEBROWSER "\xee\xa6\x9c"                   // U+e99c
#define ICON_BD_FILTER "\xee\xa6\x9d"                        // U+e99d
#define ICON_BD_FOLDER_REDIRECT "\xee\xa6\x9e"               // U+e99e
#define ICON_BD_FONT_DATA "\xee\xa6\x9f"                     // U+e99f
#define ICON_BD_FONT_PREVIEW "\xee\xa6\xa0"                  // U+e9a0
#define ICON_BD_FORCE_BOID "\xee\xa6\xa1"                    // U+e9a1
#define ICON_BD_FORCE_CHARGE "\xee\xa6\xa2"                  // U+e9a2
#define ICON_BD_FORCE_CURVE "\xee\xa6\xa3"                   // U+e9a3
#define ICON_BD_FORCE_DRAG "\xee\xa6\xa4"                    // U+e9a4
#define ICON_BD_FORCE_FLUIDFLOW "\xee\xa6\xa5"               // U+e9a5
#define ICON_BD_FORCE_FORCE "\xee\xa6\xa6"                   // U+e9a6
#define ICON_BD_FORCE_HARMONIC "\xee\xa6\xa7"                // U+e9a7
#define ICON_BD_FORCE_LENNARDJONES "\xee\xa6\xa8"            // U+e9a8
#define ICON_BD_FORCE_MAGNETIC "\xee\xa6\xa9"                // U+e9a9
#define ICON_BD_FORCE_TEXTURE "\xee\xa6\xaa"                 // U+e9aa
#define ICON_BD_FORCE_TURBULENCE "\xee\xa6\xab"              // U+e9ab
#define ICON_BD_FORCE_VORTEX "\xee\xa6\xac"                  // U+e9ac
#define ICON_BD_FORCE_WIND "\xee\xa6\xad"                    // U+e9ad
#define ICON_BD_FORWARD "\xee\xa6\xae"                       // U+e9ae
#define ICON_BD_FRAME_NEXT "\xee\xa6\xaf"                    // U+e9af
#define ICON_BD_FRAME_PREV "\xee\xa6\xb0"                    // U+e9b0
#define ICON_BD_FREEZE "\xee\xa6\xb1"                        // U+e9b1
#define ICON_BD_FULLSCREEN_ENTER "\xee\xa6\xb2"              // U+e9b2
#define ICON_BD_FULLSCREEN_EXIT "\xee\xa6\xb3"               // U+e9b3
#define ICON_BD_FUND "\xee\xa6\xb4"                          // U+e9b4
#define ICON_BD_GHOST_DISABLED "\xee\xa6\xb5"                // U+e9b5
#define ICON_BD_GHOST_ENABLED "\xee\xa6\xb6"                 // U+e9b6
#define ICON_BD_GIZMO "\xee\xa6\xb7"                         // U+e9b7
#define ICON_BD_GP_MULTIFRAME_EDITING "\xee\xa6\xb8"         // U+e9b8
#define ICON_BD_GP_ONLY_SELECTED "\xee\xa6\xb9"              // U+e9b9
#define ICON_BD_GP_SELECT_BETWEEN_STROKES "\xee\xa6\xba"     // U+e9ba
#define ICON_BD_GP_SELECT_POINTS "\xee\xa6\xbb"              // U+e9bb
#define ICON_BD_GP_SELECT_STROKES "\xee\xa6\xbc"             // U+e9bc
#define ICON_BD_GRAPH "\xee\xa6\xbd"                         // U+e9bd
#define ICON_BD_GREASEPENCIL "\xee\xa6\xbe"                  // U+e9be
#define ICON_BD_GRID "\xee\xa6\xbf"                          // U+e9bf
#define ICON_BD_GRIP "\xee\xa7\x80"                          // U+e9c0
#define ICON_BD_GROUP "\xee\xa7\x81"                         // U+e9c1
#define ICON_BD_GROUP_BONE "\xee\xa7\x82"                    // U+e9c2
#define ICON_BD_GROUP_UVS "\xee\xa7\x83"                     // U+e9c3
#define ICON_BD_GROUP_VCOL "\xee\xa7\x84"                    // U+e9c4
#define ICON_BD_GROUP_VERTEX "\xee\xa7\x85"                  // U+e9c5
#define ICON_BD_HAIR "\xee\xa7\x86"                          // U+e9c6
#define ICON_BD_HAIR_DATA "\xee\xa7\x87"                     // U+e9c7
#define ICON_BD_HAND "\xee\xa7\x88"                          // U+e9c8
#define ICON_BD_HANDLE_ALIGNED "\xee\xa7\x89"                // U+e9c9
#define ICON_BD_HANDLE_AUTO "\xee\xa7\x8a"                   // U+e9ca
#define ICON_BD_HANDLE_AUTOCLAMPED "\xee\xa7\x8b"            // U+e9cb
#define ICON_BD_HANDLE_FREE "\xee\xa7\x8c"                   // U+e9cc
#define ICON_BD_HANDLE_VECTOR "\xee\xa7\x8d"                 // U+e9cd
#define ICON_BD_HEART "\xee\xa7\x8e"                         // U+e9ce
#define ICON_BD_HELP "\xee\xa7\x8f"                          // U+e9cf
#define ICON_BD_HIDE_OFF "\xee\xa7\x90"                      // U+e9d0
#define ICON_BD_HIDE_ON "\xee\xa7\x91"                       // U+e9d1
#define ICON_BD_HOLDOUT_OFF "\xee\xa7\x92"                   // U+e9d2
#define ICON_BD_HOLDOUT_ON "\xee\xa7\x93"                    // U+e9d3
#define ICON_BD_HOME "\xee\xa7\x94"                          // U+e9d4
#define ICON_BD_HOOK "\xee\xa7\x95"                          // U+e9d5
#define ICON_BD_IMAGE "\xee\xa7\x96"                         // U+e9d6
#define ICON_BD_IMAGE_ALPHA "\xee\xa7\x97"                   // U+e9d7
#define ICON_BD_IMAGE_BACKGROUND "\xee\xa7\x98"              // U+e9d8
#define ICON_BD_IMAGE_DATA "\xee\xa7\x99"                    // U+e9d9
#define ICON_BD_IMAGE_PLANE "\xee\xa7\x9a"                   // U+e9da
#define ICON_BD_IMAGE_REFERENCE "\xee\xa7\x9b"               // U+e9db
#define ICON_BD_IMAGE_RGB "\xee\xa7\x9c"                     // U+e9dc
#define ICON_BD_IMAGE_RGB_ALPHA "\xee\xa7\x9d"               // U+e9dd
#define ICON_BD_IMAGE_ZDEPTH "\xee\xa7\x9e"                  // U+e9de
#define ICON_BD_IMGDISPLAY "\xee\xa7\x9f"                    // U+e9df
#define ICON_BD_IMPORT "\xee\xa7\xa0"                        // U+e9e0
#define ICON_BD_INDIRECT_ONLY_OFF "\xee\xa7\xa1"             // U+e9e1
#define ICON_BD_INDIRECT_ONLY_ON "\xee\xa7\xa2"              // U+e9e2
#define ICON_BD_INFO "\xee\xa7\xa3"                          // U+e9e3
#define ICON_BD_INTERPOLATE_BEZIER "\xee\xa7\xa4"            // U+e9e4
#define ICON_BD_INTERPOLATE_CIRCLE "\xee\xa7\xa5"            // U+e9e5
#define ICON_BD_INTERPOLATE_CONSTANT "\xee\xa7\xa6"          // U+e9e6
#define ICON_BD_INTERPOLATE_CUBIC "\xee\xa7\xa7"             // U+e9e7
#define ICON_BD_INTERPOLATE_EXPONENTIAL "\xee\xa7\xa8"       // U+e9e8
#define ICON_BD_INTERPOLATE_LINEAR "\xee\xa7\xa9"            // U+e9e9
#define ICON_BD_INTERPOLATE_QUAD "\xee\xa7\xaa"              // U+e9ea
#define ICON_BD_INTERPOLATE_QUARTIC "\xee\xa7\xab"           // U+e9eb
#define ICON_BD_INTERPOLATE_QUINTIC "\xee\xa7\xac"           // U+e9ec
#define ICON_BD_INTERPOLATE_SINE "\xee\xa7\xad"              // U+e9ed
#define ICON_BD_INVERSE_SQUARE_CURVE "\xee\xa7\xae"          // U+e9ee
#define ICON_BD_IPO_BACK "\xee\xa7\xaf"                      // U+e9ef
#define ICON_BD_IPO_BOUNCE "\xee\xa7\xb0"                    // U+e9f0
#define ICON_BD_IPO_EASE_IN "\xee\xa7\xb1"                   // U+e9f1
#define ICON_BD_IPO_EASE_IN_OUT "\xee\xa7\xb2"               // U+e9f2
#define ICON_BD_IPO_EASE_OUT "\xee\xa7\xb3"                  // U+e9f3
#define ICON_BD_IPO_ELASTIC "\xee\xa7\xb4"                   // U+e9f4
#define ICON_BD_ITALIC "\xee\xa7\xb5"                        // U+e9f5
#define ICON_BD_KEY_DEHLT "\xee\xa7\xb6"                     // U+e9f6
#define ICON_BD_KEY_HLT "\xee\xa7\xb7"                       // U+e9f7
#define ICON_BD_KEYFRAME "\xee\xa7\xb8"                      // U+e9f8
#define ICON_BD_KEYFRAME_HLT "\xee\xa7\xb9"                  // U+e9f9
#define ICON_BD_KEYINGSET "\xee\xa7\xba"                     // U+e9fa
#define ICON_BD_LATTICE_DATA "\xee\xa7\xbb"                  // U+e9fb
#define ICON_BD_LAYER_ACTIVE "\xee\xa7\xbc"                  // U+e9fc
#define ICON_BD_LAYER_USED "\xee\xa7\xbd"                    // U+e9fd
#define ICON_BD_LIBRARY_DATA_BROKEN "\xee\xa7\xbe"           // U+e9fe
#define ICON_BD_LIBRARY_DATA_DIRECT "\xee\xa7\xbf"           // U+e9ff
#define ICON_BD_LIBRARY_DATA_INDIRECT "\xee\xa8\x80"         // U+ea00
#define ICON_BD_LIBRARY_DATA_OVERRIDE "\xee\xa8\x81"         // U+ea01
#define ICON_BD_LIGHT "\xee\xa8\x82"                         // U+ea02
#define ICON_BD_LIGHT_AREA "\xee\xa8\x83"                    // U+ea03
#define ICON_BD_LIGHT_DATA "\xee\xa8\x84"                    // U+ea04
#define ICON_BD_LIGHT_HEMI "\xee\xa8\x85"                    // U+ea05
#define ICON_BD_LIGHT_POINT "\xee\xa8\x86"                   // U+ea06
#define ICON_BD_LIGHT_SPOT "\xee\xa8\x87"                    // U+ea07
#define ICON_BD_LIGHT_SUN "\xee\xa8\x88"                     // U+ea08
#define ICON_BD_LIGHTPROBE_CUBEMAP "\xee\xa8\x89"            // U+ea09
#define ICON_BD_LIGHTPROBE_GRID "\xee\xa8\x8a"               // U+ea0a
#define ICON_BD_LIGHTPROBE_PLANAR "\xee\xa8\x8b"             // U+ea0b
#define ICON_BD_LINE_DATA "\xee\xa8\x8c"                     // U+ea0c
#define ICON_BD_LINEAR_CURVE "\xee\xa8\x8d"                  // U+ea0d
#define ICON_BD_LINENUMBERS_OFF "\xee\xa8\x8e"               // U+ea0e
#define ICON_BD_LINENUMBERS_ON "\xee\xa8\x8f"                // U+ea0f
#define ICON_BD_LINK_BLEND "\xee\xa8\x90"                    // U+ea10
#define ICON_BD_LINKED "\xee\xa8\x91"                        // U+ea11
#define ICON_BD_LOCK_VIEW_OFF "\xee\xa8\x92"                 // U+ea12
#define ICON_BD_LOCK_VIEW_ON "\xee\xa8\x93"                  // U+ea13
#define ICON_BD_LOCKED "\xee\xa8\x94"                        // U+ea14
#define ICON_BD_LONGDISPLAY "\xee\xa8\x95"                   // U+ea15
#define ICON_BD_LOOP_BACK "\xee\xa8\x96"                     // U+ea16
#define ICON_BD_LOOP_FORWARDS "\xee\xa8\x97"                 // U+ea17
#define ICON_BD_MARKER "\xee\xa8\x98"                        // U+ea18
#define ICON_BD_MARKER_HLT "\xee\xa8\x99"                    // U+ea19
#define ICON_BD_MAT_CLOTH "\xee\xa8\x9a"                     // U+ea1a
#define ICON_BD_MAT_CUBE "\xee\xa8\x9b"                      // U+ea1b
#define ICON_BD_MAT_FLUID "\xee\xa8\x9c"                     // U+ea1c
#define ICON_BD_MAT_PLANE "\xee\xa8\x9d"                     // U+ea1d
#define ICON_BD_MAT_SHADERBALL "\xee\xa8\x9e"                // U+ea1e
#define ICON_BD_MAT_SPHERE "\xee\xa8\x9f"                    // U+ea1f
#define ICON_BD_MAT_SPHERE_SKY "\xee\xa8\xa0"                // U+ea20
#define ICON_BD_MATERIAL "\xee\xa8\xa1"                      // U+ea21
#define ICON_BD_MATERIAL_DATA "\xee\xa8\xa2"                 // U+ea22
#define ICON_BD_MEMORY "\xee\xa8\xa3"                        // U+ea23
#define ICON_BD_MENU_PANEL "\xee\xa8\xa4"                    // U+ea24
#define ICON_BD_MESH_CAPSULE "\xee\xa8\xa5"                  // U+ea25
#define ICON_BD_MESH_CIRCLE "\xee\xa8\xa6"                   // U+ea26
#define ICON_BD_MESH_CONE "\xee\xa8\xa7"                     // U+ea27
#define ICON_BD_MESH_CUBE "\xee\xa8\xa8"                     // U+ea28
#define ICON_BD_MESH_CYLINDER "\xee\xa8\xa9"                 // U+ea29
#define ICON_BD_MESH_DATA "\xee\xa8\xaa"                     // U+ea2a
#define ICON_BD_MESH_GRID "\xee\xa8\xab"                     // U+ea2b
#define ICON_BD_MESH_ICOSPHERE "\xee\xa8\xac"                // U+ea2c
#define ICON_BD_MESH_MONKEY "\xee\xa8\xad"                   // U+ea2d
#define ICON_BD_MESH_PLANE "\xee\xa8\xae"                    // U+ea2e
#define ICON_BD_MESH_TORUS "\xee\xa8\xaf"                    // U+ea2f
#define ICON_BD_MESH_UVSPHERE "\xee\xa8\xb0"                 // U+ea30
#define ICON_BD_META_BALL "\xee\xa8\xb1"                     // U+ea31
#define ICON_BD_META_CAPSULE "\xee\xa8\xb2"                  // U+ea32
#define ICON_BD_META_CUBE "\xee\xa8\xb3"                     // U+ea33
#define ICON_BD_META_DATA "\xee\xa8\xb4"                     // U+ea34
#define ICON_BD_META_ELLIPSOID "\xee\xa8\xb5"                // U+ea35
#define ICON_BD_META_PLANE "\xee\xa8\xb6"                    // U+ea36
#define ICON_BD_MOD_ARMATURE "\xee\xa8\xb7"                  // U+ea37
#define ICON_BD_MOD_ARRAY "\xee\xa8\xb8"                     // U+ea38
#define ICON_BD_MOD_BEVEL "\xee\xa8\xb9"                     // U+ea39
#define ICON_BD_MOD_BOOLEAN "\xee\xa8\xba"                   // U+ea3a
#define ICON_BD_MOD_BUILD "\xee\xa8\xbb"                     // U+ea3b
#define ICON_BD_MOD_CAST "\xee\xa8\xbc"                      // U+ea3c
#define ICON_BD_MOD_CLOTH "\xee\xa8\xbd"                     // U+ea3d
#define ICON_BD_MOD_CURVE "\xee\xa8\xbe"                     // U+ea3e
#define ICON_BD_MOD_DATA_TRANSFER "\xee\xa8\xbf"             // U+ea3f
#define ICON_BD_MOD_DECIM "\xee\xa9\x80"                     // U+ea40
#define ICON_BD_MOD_DISPLACE "\xee\xa9\x81"                  // U+ea41
#define ICON_BD_MOD_DYNAMICPAINT "\xee\xa9\x82"              // U+ea42
#define ICON_BD_MOD_EDGESPLIT "\xee\xa9\x83"                 // U+ea43
#define ICON_BD_MOD_EXPLODE "\xee\xa9\x84"                   // U+ea44
#define ICON_BD_MOD_FLUID "\xee\xa9\x85"                     // U+ea45
#define ICON_BD_MOD_FLUIDSIM "\xee\xa9\x86"                  // U+ea46
#define ICON_BD_MOD_HUE_SATURATION "\xee\xa9\x87"            // U+ea47
#define ICON_BD_MOD_INSTANCE "\xee\xa9\x88"                  // U+ea48
#define ICON_BD_MOD_LATTICE "\xee\xa9\x89"                   // U+ea49
#define ICON_BD_MOD_MASK "\xee\xa9\x8a"                      // U+ea4a
#define ICON_BD_MOD_MESHDEFORM "\xee\xa9\x8b"                // U+ea4b
#define ICON_BD_MOD_MIRROR "\xee\xa9\x8c"                    // U+ea4c
#define ICON_BD_MOD_MULTIRES "\xee\xa9\x8d"                  // U+ea4d
#define ICON_BD_MOD_NOISE "\xee\xa9\x8e"                     // U+ea4e
#define ICON_BD_MOD_NORMALEDIT "\xee\xa9\x8f"                // U+ea4f
#define ICON_BD_MOD_OCEAN "\xee\xa9\x90"                     // U+ea50
#define ICON_BD_MOD_OFFSET "\xee\xa9\x91"                    // U+ea51
#define ICON_BD_MOD_OPACITY "\xee\xa9\x92"                   // U+ea52
#define ICON_BD_MOD_PARTICLE_INSTANCE "\xee\xa9\x93"         // U+ea53
#define ICON_BD_MOD_PARTICLES "\xee\xa9\x94"                 // U+ea54
#define ICON_BD_MOD_PHYSICS "\xee\xa9\x95"                   // U+ea55
#define ICON_BD_MOD_REMESH "\xee\xa9\x96"                    // U+ea56
#define ICON_BD_MOD_SCREW "\xee\xa9\x97"                     // U+ea57
#define ICON_BD_MOD_SHRINKWRAP "\xee\xa9\x98"                // U+ea58
#define ICON_BD_MOD_SIMPLEDEFORM "\xee\xa9\x99"              // U+ea59
#define ICON_BD_MOD_SIMPLIFY "\xee\xa9\x9a"                  // U+ea5a
#define ICON_BD_MOD_SKIN "\xee\xa9\x9b"                      // U+ea5b
#define ICON_BD_MOD_SMOOTH "\xee\xa9\x9c"                    // U+ea5c
#define ICON_BD_MOD_SOFT "\xee\xa9\x9d"                      // U+ea5d
#define ICON_BD_MOD_SOLIDIFY "\xee\xa9\x9e"                  // U+ea5e
#define ICON_BD_MOD_SUBSURF "\xee\xa9\x9f"                   // U+ea5f
#define ICON_BD_MOD_THICKNESS "\xee\xa9\xa0"                 // U+ea60
#define ICON_BD_MOD_TIME "\xee\xa9\xa1"                      // U+ea61
#define ICON_BD_MOD_TINT "\xee\xa9\xa2"                      // U+ea62
#define ICON_BD_MOD_TRIANGULATE "\xee\xa9\xa3"               // U+ea63
#define ICON_BD_MOD_UVPROJECT "\xee\xa9\xa4"                 // U+ea64
#define ICON_BD_MOD_VERTEX_WEIGHT "\xee\xa9\xa5"             // U+ea65
#define ICON_BD_MOD_WARP "\xee\xa9\xa6"                      // U+ea66
#define ICON_BD_MOD_WAVE "\xee\xa9\xa7"                      // U+ea67
#define ICON_BD_MOD_WIREFRAME "\xee\xa9\xa8"                 // U+ea68
#define ICON_BD_MODIFIER "\xee\xa9\xa9"                      // U+ea69
#define ICON_BD_MODIFIER_DATA "\xee\xa9\xaa"                 // U+ea6a
#define ICON_BD_MODIFIER_OFF "\xee\xa9\xab"                  // U+ea6b
#define ICON_BD_MODIFIER_ON "\xee\xa9\xac"                   // U+ea6c
#define ICON_BD_MONKEY "\xee\xa9\xad"                        // U+ea6d
#define ICON_BD_MOUSE_LMB "\xee\xa9\xae"                     // U+ea6e
#define ICON_BD_MOUSE_LMB_DRAG "\xee\xa9\xaf"                // U+ea6f
#define ICON_BD_MOUSE_MMB "\xee\xa9\xb0"                     // U+ea70
#define ICON_BD_MOUSE_MMB_DRAG "\xee\xa9\xb1"                // U+ea71
#define ICON_BD_MOUSE_MOVE "\xee\xa9\xb2"                    // U+ea72
#define ICON_BD_MOUSE_RMB "\xee\xa9\xb3"                     // U+ea73
#define ICON_BD_MOUSE_RMB_DRAG "\xee\xa9\xb4"                // U+ea74
#define ICON_BD_MUTE_IPO_OFF "\xee\xa9\xb5"                  // U+ea75
#define ICON_BD_MUTE_IPO_ON "\xee\xa9\xb6"                   // U+ea76
#define ICON_BD_NETWORK_DRIVE "\xee\xa9\xb7"                 // U+ea77
#define ICON_BD_NEW_FOLDER "\xee\xa9\xb8"                    // U+ea78
#define ICON_BD_NEXT_KEYFRAME "\xee\xa9\xb9"                 // U+ea79
#define ICON_BD_NLA "\xee\xa9\xba"                           // U+ea7a
#define ICON_BD_NLA_PUSHDOWN "\xee\xa9\xbb"                  // U+ea7b
#define ICON_BD_NO_CURVE "\xee\xa9\xbc"                      // U+ea7c
#define ICON_BD_NODE "\xee\xa9\xbd"                          // U+ea7d
#define ICON_BD_NODE_COMPOSITING "\xee\xa9\xbe"              // U+ea7e
#define ICON_BD_NODE_CORNER "\xee\xa9\xbf"                   // U+ea7f
#define ICON_BD_NODE_INSERT_OFF "\xee\xaa\x80"               // U+ea80
#define ICON_BD_NODE_INSERT_ON "\xee\xaa\x81"                // U+ea81
#define ICON_BD_NODE_MATERIAL "\xee\xaa\x82"                 // U+ea82
#define ICON_BD_NODE_SEL "\xee\xaa\x83"                      // U+ea83
#define ICON_BD_NODE_SIDE "\xee\xaa\x84"                     // U+ea84
#define ICON_BD_NODE_TEXTURE "\xee\xaa\x85"                  // U+ea85
#define ICON_BD_NODE_TOP "\xee\xaa\x86"                      // U+ea86
#define ICON_BD_NODETREE "\xee\xaa\x87"                      // U+ea87
#define ICON_BD_NORMALIZE_FCURVES "\xee\xaa\x88"             // U+ea88
#define ICON_BD_NORMALS_FACE "\xee\xaa\x89"                  // U+ea89
#define ICON_BD_NORMALS_VERTEX "\xee\xaa\x8a"                // U+ea8a
#define ICON_BD_NORMALS_VERTEX_FACE "\xee\xaa\x8b"           // U+ea8b
#define ICON_BD_OBJECT_DATA "\xee\xaa\x8c"                   // U+ea8c
#define ICON_BD_OBJECT_DATAMODE "\xee\xaa\x8d"               // U+ea8d
#define ICON_BD_OBJECT_HIDDEN "\xee\xaa\x8e"                 // U+ea8e
#define ICON_BD_OBJECT_ORIGIN "\xee\xaa\x8f"                 // U+ea8f
#define ICON_BD_ONIONSKIN_OFF "\xee\xaa\x90"                 // U+ea90
#define ICON_BD_ONIONSKIN_ON "\xee\xaa\x91"                  // U+ea91
#define ICON_BD_OPTIONS "\xee\xaa\x92"                       // U+ea92
#define ICON_BD_ORIENTATION_CURSOR "\xee\xaa\x93"            // U+ea93
#define ICON_BD_ORIENTATION_GIMBAL "\xee\xaa\x94"            // U+ea94
#define ICON_BD_ORIENTATION_GLOBAL "\xee\xaa\x95"            // U+ea95
#define ICON_BD_ORIENTATION_LOCAL "\xee\xaa\x96"             // U+ea96
#define ICON_BD_ORIENTATION_NORMAL "\xee\xaa\x97"            // U+ea97
#define ICON_BD_ORIENTATION_VIEW "\xee\xaa\x98"              // U+ea98
#define ICON_BD_ORPHAN_DATA "\xee\xaa\x99"                   // U+ea99
#define ICON_BD_OUTLINER "\xee\xaa\x9a"                      // U+ea9a
#define ICON_BD_OUTLINER_COLLECTION "\xee\xaa\x9b"           // U+ea9b
#define ICON_BD_OUTLINER_DATA_ARMATURE "\xee\xaa\x9c"        // U+ea9c
#define ICON_BD_OUTLINER_DATA_CAMERA "\xee\xaa\x9d"          // U+ea9d
#define ICON_BD_OUTLINER_DATA_CURVE "\xee\xaa\x9e"           // U+ea9e
#define ICON_BD_OUTLINER_DATA_EMPTY "\xee\xaa\x9f"           // U+ea9f
#define ICON_BD_OUTLINER_DATA_FONT "\xee\xaa\xa0"            // U+eaa0
#define ICON_BD_OUTLINER_DATA_GP_LAYER "\xee\xaa\xa1"        // U+eaa1
#define ICON_BD_OUTLINER_DATA_GREASEPENCIL "\xee\xaa\xa2"    // U+eaa2
#define ICON_BD_OUTLINER_DATA_HAIR "\xee\xaa\xa3"            // U+eaa3
#define ICON_BD_OUTLINER_DATA_LATTICE "\xee\xaa\xa4"         // U+eaa4
#define ICON_BD_OUTLINER_DATA_LIGHT "\xee\xaa\xa5"           // U+eaa5
#define ICON_BD_OUTLINER_DATA_LIGHTPROBE "\xee\xaa\xa6"      // U+eaa6
#define ICON_BD_OUTLINER_DATA_MESH "\xee\xaa\xa7"            // U+eaa7
#define ICON_BD_OUTLINER_DATA_META "\xee\xaa\xa8"            // U+eaa8
#define ICON_BD_OUTLINER_DATA_POINTCLOUD "\xee\xaa\xa9"      // U+eaa9
#define ICON_BD_OUTLINER_DATA_SPEAKER "\xee\xaa\xaa"         // U+eaaa
#define ICON_BD_OUTLINER_DATA_SURFACE "\xee\xaa\xab"         // U+eaab
#define ICON_BD_OUTLINER_DATA_VOLUME "\xee\xaa\xac"          // U+eaac
#define ICON_BD_OUTLINER_OB_ARMATURE "\xee\xaa\xad"          // U+eaad
#define ICON_BD_OUTLINER_OB_CAMERA "\xee\xaa\xae"            // U+eaae
#define ICON_BD_OUTLINER_OB_CURVE "\xee\xaa\xaf"             // U+eaaf
#define ICON_BD_OUTLINER_OB_EMPTY "\xee\xaa\xb0"             // U+eab0
#define ICON_BD_OUTLINER_OB_FONT "\xee\xaa\xb1"              // U+eab1
#define ICON_BD_OUTLINER_OB_FORCE_FIELD "\xee\xaa\xb2"       // U+eab2
#define ICON_BD_OUTLINER_OB_GREASEPENCIL "\xee\xaa\xb3"      // U+eab3
#define ICON_BD_OUTLINER_OB_GROUP_INSTANCE "\xee\xaa\xb4"    // U+eab4
#define ICON_BD_OUTLINER_OB_HAIR "\xee\xaa\xb5"              // U+eab5
#define ICON_BD_OUTLINER_OB_IMAGE "\xee\xaa\xb6"             // U+eab6
#define ICON_BD_OUTLINER_OB_LATTICE "\xee\xaa\xb7"           // U+eab7
#define ICON_BD_OUTLINER_OB_LIGHT "\xee\xaa\xb8"             // U+eab8
#define ICON_BD_OUTLINER_OB_LIGHTPROBE "\xee\xaa\xb9"        // U+eab9
#define ICON_BD_OUTLINER_OB_MESH "\xee\xaa\xba"              // U+eaba
#define ICON_BD_OUTLINER_OB_META "\xee\xaa\xbb"              // U+eabb
#define ICON_BD_OUTLINER_OB_POINTCLOUD "\xee\xaa\xbc"        // U+eabc
#define ICON_BD_OUTLINER_OB_SPEAKER "\xee\xaa\xbd"           // U+eabd
#define ICON_BD_OUTLINER_OB_SURFACE "\xee\xaa\xbe"           // U+eabe
#define ICON_BD_OUTLINER_OB_VOLUME "\xee\xaa\xbf"            // U+eabf
#define ICON_BD_OUTPUT "\xee\xab\x80"                        // U+eac0
#define ICON_BD_OVERLAY "\xee\xab\x81"                       // U+eac1
#define ICON_BD_PACKAGE "\xee\xab\x82"                       // U+eac2
#define ICON_BD_PANEL_CLOSE "\xee\xab\x83"                   // U+eac3
#define ICON_BD_PARTICLE_DATA "\xee\xab\x84"                 // U+eac4
#define ICON_BD_PARTICLE_PATH "\xee\xab\x85"                 // U+eac5
#define ICON_BD_PARTICLE_POINT "\xee\xab\x86"                // U+eac6
#define ICON_BD_PARTICLE_TIP "\xee\xab\x87"                  // U+eac7
#define ICON_BD_PARTICLEMODE "\xee\xab\x88"                  // U+eac8
#define ICON_BD_PARTICLES "\xee\xab\x89"                     // U+eac9
#define ICON_BD_PASTE_DOWN "\xee\xab\x8a"                    // U+eaca
#define ICON_BD_PASTE_FLIP_DOWN "\xee\xab\x8b"               // U+eacb
#define ICON_BD_PASTE_FLIP_UP "\xee\xab\x8c"                 // U+eacc
#define ICON_BD_PAUSE "\xee\xab\x8d"                         // U+eacd
#define ICON_BD_PHYSICS "\xee\xab\x8e"                       // U+eace
#define ICON_BD_PINNED "\xee\xab\x8f"                        // U+eacf
#define ICON_BD_PIVOT_ACTIVE "\xee\xab\x90"                  // U+ead0
#define ICON_BD_PIVOT_CURSOR "\xee\xab\x91"                  // U+ead1
#define ICON_BD_PIVOT_INDIVIDUAL "\xee\xab\x92"              // U+ead2
#define ICON_BD_PIVOT_MEDIAN "\xee\xab\x93"                  // U+ead3
#define ICON_BD_PIVOT_OBOUNDING_BOX "\xee\xab\x94"           // U+ead4
#define ICON_BD_PLAY "\xee\xab\x95"                          // U+ead5
#define ICON_BD_PLAY_REVERSE "\xee\xab\x96"                  // U+ead6
#define ICON_BD_PLAY_SOUND "\xee\xab\x97"                    // U+ead7
#define ICON_BD_PLUGIN "\xee\xab\x98"                        // U+ead8
#define ICON_BD_PLUS "\xee\xab\x99"                          // U+ead9
#define ICON_BD_PMARKER "\xee\xab\x9a"                       // U+eada
#define ICON_BD_PMARKER_ACT "\xee\xab\x9b"                   // U+eadb
#define ICON_BD_PMARKER_SEL "\xee\xab\x9c"                   // U+eadc
#define ICON_BD_POINTCLOUD_DATA "\xee\xab\x9d"               // U+eadd
#define ICON_BD_POSE_HLT "\xee\xab\x9e"                      // U+eade
#define ICON_BD_PREFERENCES "\xee\xab\x9f"                   // U+eadf
#define ICON_BD_PRESET "\xee\xab\xa0"                        // U+eae0
#define ICON_BD_PRESET_NEW "\xee\xab\xa1"                    // U+eae1
#define ICON_BD_PREV_KEYFRAME "\xee\xab\xa2"                 // U+eae2
#define ICON_BD_PREVIEW_RANGE "\xee\xab\xa3"                 // U+eae3
#define ICON_BD_PROPERTIES "\xee\xab\xa4"                    // U+eae4
#define ICON_BD_PROPORTIONAL_CENTER_ON "\xee\xab\xa5"        // U+eae5
#define ICON_BD_PROPORTIONAL_OFF "\xee\xab\xa6"              // U+eae6
#define ICON_BD_PROPORTIONAL_ON "\xee\xab\xa7"               // U+eae7
#define ICON_BD_PROPORTIONAL_PROJECTED "\xee\xab\xa8"        // U+eae8
#define ICON_BD_QUESTION "\xee\xab\xa9"                      // U+eae9
#define ICON_BD_QUIT "\xee\xab\xaa"                          // U+eaea
#define ICON_BD_RADIOBUT_OFF "\xee\xab\xab"                  // U+eaeb
#define ICON_BD_RADIOBUT_ON "\xee\xab\xac"                   // U+eaec
#define ICON_BD_REC "\xee\xab\xad"                           // U+eaed
#define ICON_BD_RECOVER_LAST "\xee\xab\xae"                  // U+eaee
#define ICON_BD_REMOVE "\xee\xab\xaf"                        // U+eaef
#define ICON_BD_RENDER_ANIMATION "\xee\xab\xb0"              // U+eaf0
#define ICON_BD_RENDER_RESULT "\xee\xab\xb1"                 // U+eaf1
#define ICON_BD_RENDER_STILL "\xee\xab\xb2"                  // U+eaf2
#define ICON_BD_RENDERLAYERS "\xee\xab\xb3"                  // U+eaf3
#define ICON_BD_RESTRICT_COLOR_OFF "\xee\xab\xb4"            // U+eaf4
#define ICON_BD_RESTRICT_COLOR_ON "\xee\xab\xb5"             // U+eaf5
#define ICON_BD_RESTRICT_INSTANCED_OFF "\xee\xab\xb6"        // U+eaf6
#define ICON_BD_RESTRICT_INSTANCED_ON "\xee\xab\xb7"         // U+eaf7
#define ICON_BD_RESTRICT_RENDER_OFF "\xee\xab\xb8"           // U+eaf8
#define ICON_BD_RESTRICT_RENDER_ON "\xee\xab\xb9"            // U+eaf9
#define ICON_BD_RESTRICT_SELECT_OFF "\xee\xab\xba"           // U+eafa
#define ICON_BD_RESTRICT_SELECT_ON "\xee\xab\xbb"            // U+eafb
#define ICON_BD_RESTRICT_VIEW_OFF "\xee\xab\xbc"             // U+eafc
#define ICON_BD_RESTRICT_VIEW_ON "\xee\xab\xbd"              // U+eafd
#define ICON_BD_REW "\xee\xab\xbe"                           // U+eafe
#define ICON_BD_RIGHTARROW "\xee\xab\xbf"                    // U+eaff
#define ICON_BD_RIGHTARROW_THIN "\xee\xac\x80"               // U+eb00
#define ICON_BD_RIGID_BODY "\xee\xac\x81"                    // U+eb01
#define ICON_BD_RIGID_BODY_CONSTRAINT "\xee\xac\x82"         // U+eb02
#define ICON_BD_RNA "\xee\xac\x83"                           // U+eb03
#define ICON_BD_RNA_ADD "\xee\xac\x84"                       // U+eb04
#define ICON_BD_ROOT_CURVE "\xee\xac\x85"                    // U+eb05
#define ICON_BD_ROUND_CURVE "\xee\xac\x86"                   // U+eb06
#define ICON_BD_SCENE "\xee\xac\x87"                         // U+eb07
#define ICON_BD_SCENE_DATA "\xee\xac\x88"                    // U+eb08
#define ICON_BD_SCREEN_BACK "\xee\xac\x89"                   // U+eb09
#define ICON_BD_SCRIPT "\xee\xac\x8a"                        // U+eb0a
#define ICON_BD_SCRIPT_PLUGINS "\xee\xac\x8b"                // U+eb0b
#define ICON_BD_SCULPTMODE_HLT "\xee\xac\x8c"                // U+eb0c
#define ICON_BD_SELECT_DIFFERENCE "\xee\xac\x8d"             // U+eb0d
#define ICON_BD_SELECT_EXTEND "\xee\xac\x8e"                 // U+eb0e
#define ICON_BD_SELECT_INTERSECT "\xee\xac\x8f"              // U+eb0f
#define ICON_BD_SELECT_SET "\xee\xac\x90"                    // U+eb10
#define ICON_BD_SELECT_SUBTRACT "\xee\xac\x91"               // U+eb11
#define ICON_BD_SEQ_CHROMA_SCOPE "\xee\xac\x92"              // U+eb12
#define ICON_BD_SEQ_HISTOGRAM "\xee\xac\x93"                 // U+eb13
#define ICON_BD_SEQ_LUMA_WAVEFORM "\xee\xac\x94"             // U+eb14
#define ICON_BD_SEQ_PREVIEW "\xee\xac\x95"                   // U+eb15
#define ICON_BD_SEQ_SEQUENCER "\xee\xac\x96"                 // U+eb16
#define ICON_BD_SEQ_SPLITVIEW "\xee\xac\x97"                 // U+eb17
#define ICON_BD_SEQ_STRIP_DUPLICATE "\xee\xac\x98"           // U+eb18
#define ICON_BD_SEQ_STRIP_META "\xee\xac\x99"                // U+eb19
#define ICON_BD_SEQUENCE "\xee\xac\x9a"                      // U+eb1a
#define ICON_BD_SETTINGS "\xee\xac\x9b"                      // U+eb1b
#define ICON_BD_SHADERFX "\xee\xac\x9c"                      // U+eb1c
#define ICON_BD_SHADING_BOUNDING_BOX "\xee\xac\x9d"          // U+eb1d
#define ICON_BD_SHADING_RENDERED "\xee\xac\x9e"              // U+eb1e
#define ICON_BD_SHADING_SOLID "\xee\xac\x9f"                 // U+eb1f
#define ICON_BD_SHADING_TEXTURE "\xee\xac\xa0"               // U+eb20
#define ICON_BD_SHADING_WIRE "\xee\xac\xa1"                  // U+eb21
#define ICON_BD_SHAPEKEY_DATA "\xee\xac\xa2"                 // U+eb22
#define ICON_BD_SHARP_CURVE "\xee\xac\xa3"                   // U+eb23
#define ICON_BD_SHORTDISPLAY "\xee\xac\xa4"                  // U+eb24
#define ICON_BD_SMALL_CAPS "\xee\xac\xa5"                    // U+eb25
#define ICON_BD_SMOOTH_CURVE "\xee\xac\xa6"                  // U+eb26
#define ICON_BD_SNAP_EDGE "\xee\xac\xa7"                     // U+eb27
#define ICON_BD_SNAP_FACE "\xee\xac\xa8"                     // U+eb28
#define ICON_BD_SNAP_FACE_CENTER "\xee\xac\xa9"              // U+eb29
#define ICON_BD_SNAP_GRID "\xee\xac\xaa"                     // U+eb2a
#define ICON_BD_SNAP_INCREMENT "\xee\xac\xab"                // U+eb2b
#define ICON_BD_SNAP_MIDPOINT "\xee\xac\xac"                 // U+eb2c
#define ICON_BD_SNAP_NORMAL "\xee\xac\xad"                   // U+eb2d
#define ICON_BD_SNAP_OFF "\xee\xac\xae"                      // U+eb2e
#define ICON_BD_SNAP_ON "\xee\xac\xaf"                       // U+eb2f
#define ICON_BD_SNAP_PEEL_OBJECT "\xee\xac\xb0"              // U+eb30
#define ICON_BD_SNAP_PERPENDICULAR "\xee\xac\xb1"            // U+eb31
#define ICON_BD_SNAP_VERTEX "\xee\xac\xb2"                   // U+eb32
#define ICON_BD_SNAP_VOLUME "\xee\xac\xb3"                   // U+eb33
#define ICON_BD_SOLO_OFF "\xee\xac\xb4"                      // U+eb34
#define ICON_BD_SOLO_ON "\xee\xac\xb5"                       // U+eb35
#define ICON_BD_SORT_ALPHA "\xee\xac\xb6"                    // U+eb36
#define ICON_BD_SORT_ASC "\xee\xac\xb7"                      // U+eb37
#define ICON_BD_SORT_BY_EXT "\xee\xac\xb8"                   // U+eb38
#define ICON_BD_SORT_DESC "\xee\xac\xb9"                     // U+eb39
#define ICON_BD_SORT_SIZE "\xee\xac\xba"                     // U+eb3a
#define ICON_BD_SORT_TIME "\xee\xac\xbb"                     // U+eb3b
#define ICON_BD_SOUND "\xee\xac\xbc"                         // U+eb3c
#define ICON_BD_SPEAKER "\xee\xac\xbd"                       // U+eb3d
#define ICON_BD_SPHERE "\xee\xac\xbe"                        // U+eb3e
#define ICON_BD_SPHERE_CURVE "\xee\xac\xbf"                  // U+eb3f
#define ICON_BD_SPREADSHEET "\xee\xad\x80"                   // U+eb40
#define ICON_BD_STATUSBAR "\xee\xad\x81"                     // U+eb41
#define ICON_BD_STICKY_UVS_DISABLE "\xee\xad\x82"            // U+eb42
#define ICON_BD_STICKY_UVS_LOC "\xee\xad\x83"                // U+eb43
#define ICON_BD_STICKY_UVS_VERT "\xee\xad\x84"               // U+eb44
#define ICON_BD_STRANDS "\xee\xad\x85"                       // U+eb45
#define ICON_BD_STROKE "\xee\xad\x86"                        // U+eb46
#define ICON_BD_STYLUS_PRESSURE "\xee\xad\x87"               // U+eb47
#define ICON_BD_SURFACE_DATA "\xee\xad\x88"                  // U+eb48
#define ICON_BD_SURFACE_NCIRCLE "\xee\xad\x89"               // U+eb49
#define ICON_BD_SURFACE_NCURVE "\xee\xad\x8a"                // U+eb4a
#define ICON_BD_SURFACE_NCYLINDER "\xee\xad\x8b"             // U+eb4b
#define ICON_BD_SURFACE_NSPHERE "\xee\xad\x8c"               // U+eb4c
#define ICON_BD_SURFACE_NSURFACE "\xee\xad\x8d"              // U+eb4d
#define ICON_BD_SURFACE_NTORUS "\xee\xad\x8e"                // U+eb4e
#define ICON_BD_SYNTAX_OFF "\xee\xad\x8f"                    // U+eb4f
#define ICON_BD_SYNTAX_ON "\xee\xad\x90"                     // U+eb50
#define ICON_BD_SYSTEM "\xee\xad\x91"                        // U+eb51
#define ICON_BD_TEMP "\xee\xad\x92"                          // U+eb52
#define ICON_BD_TEXT "\xee\xad\x93"                          // U+eb53
#define ICON_BD_TEXTURE "\xee\xad\x94"                       // U+eb54
#define ICON_BD_TEXTURE_DATA "\xee\xad\x95"                  // U+eb55
#define ICON_BD_THREE_DOTS "\xee\xad\x96"                    // U+eb56
#define ICON_BD_TIME "\xee\xad\x97"                          // U+eb57
#define ICON_BD_TOOL_SETTINGS "\xee\xad\x98"                 // U+eb58
#define ICON_BD_TOPBAR "\xee\xad\x99"                        // U+eb59
#define ICON_BD_TPAINT_HLT "\xee\xad\x9a"                    // U+eb5a
#define ICON_BD_TRACKER "\xee\xad\x9b"                       // U+eb5b
#define ICON_BD_TRACKER_DATA "\xee\xad\x9c"                  // U+eb5c
#define ICON_BD_TRACKING "\xee\xad\x9d"                      // U+eb5d
#define ICON_BD_TRACKING_BACKWARDS "\xee\xad\x9e"            // U+eb5e
#define ICON_BD_TRACKING_BACKWARDS_SINGLE "\xee\xad\x9f"     // U+eb5f
#define ICON_BD_TRACKING_CLEAR_BACKWARDS "\xee\xad\xa0"      // U+eb60
#define ICON_BD_TRACKING_CLEAR_FORWARDS "\xee\xad\xa1"       // U+eb61
#define ICON_BD_TRACKING_FORWARDS "\xee\xad\xa2"             // U+eb62
#define ICON_BD_TRACKING_FORWARDS_SINGLE "\xee\xad\xa3"      // U+eb63
#define ICON_BD_TRACKING_REFINE_BACKWARDS "\xee\xad\xa4"     // U+eb64
#define ICON_BD_TRACKING_REFINE_FORWARDS "\xee\xad\xa5"      // U+eb65
#define ICON_BD_TRANSFORM_ORIGINS "\xee\xad\xa6"             // U+eb66
#define ICON_BD_TRASH "\xee\xad\xa7"                         // U+eb67
#define ICON_BD_TRIA_DOWN "\xee\xad\xa8"                     // U+eb68
#define ICON_BD_TRIA_DOWN_BAR "\xee\xad\xa9"                 // U+eb69
#define ICON_BD_TRIA_LEFT "\xee\xad\xaa"                     // U+eb6a
#define ICON_BD_TRIA_LEFT_BAR "\xee\xad\xab"                 // U+eb6b
#define ICON_BD_TRIA_RIGHT "\xee\xad\xac"                    // U+eb6c
#define ICON_BD_TRIA_RIGHT_BAR "\xee\xad\xad"                // U+eb6d
#define ICON_BD_TRIA_UP "\xee\xad\xae"                       // U+eb6e
#define ICON_BD_TRIA_UP_BAR "\xee\xad\xaf"                   // U+eb6f
#define ICON_BD_UGLYPACKAGE "\xee\xad\xb0"                   // U+eb70
#define ICON_BD_UNDERLINE "\xee\xad\xb1"                     // U+eb71
#define ICON_BD_UNLINKED "\xee\xad\xb2"                      // U+eb72
#define ICON_BD_UNLOCKED "\xee\xad\xb3"                      // U+eb73
#define ICON_BD_UNPINNED "\xee\xad\xb4"                      // U+eb74
#define ICON_BD_URL "\xee\xad\xb5"                           // U+eb75
#define ICON_BD_USER "\xee\xad\xb6"                          // U+eb76
#define ICON_BD_UV "\xee\xad\xb7"                            // U+eb77
#define ICON_BD_UV_DATA "\xee\xad\xb8"                       // U+eb78
#define ICON_BD_UV_EDGE_SELECT "\xee\xad\xb9"                // U+eb79
#define ICON_BD_UV_FACE_SELECT "\xee\xad\xba"                // U+eb7a
#define ICON_BD_UV_ISLANDS_SELECT "\xee\xad\xbb"             // U+eb7b
#define ICON_BD_UV_SYNC_SELECT "\xee\xad\xbc"                // U+eb7c
#define ICON_BD_UV_VERTEX_SELECT "\xee\xad\xbd"              // U+eb7d
#define ICON_BD_VERTEX_SELECT "\xee\xad\xbe"                 // U+eb7e
#define ICON_BD_VIEW_CAMERA "\xee\xad\xbf"                   // U+eb7f
#define ICON_BD_VIEW_ORTHO "\xee\xae\x80"                    // U+eb80
#define ICON_BD_VIEW_PAN "\xee\xae\x81"                      // U+eb81
#define ICON_BD_VIEW_PERSPECTIVE "\xee\xae\x82"              // U+eb82
#define ICON_BD_VIEW_ZOOM "\xee\xae\x83"                     // U+eb83
#define ICON_BD_VIEW3D "\xee\xae\x84"                        // U+eb84
#define ICON_BD_VIEWZOOM "\xee\xae\x85"                      // U+eb85
#define ICON_BD_VISUAL_SELECTION_DISABLED "\xee\xae\x86"     // U+eb86
#define ICON_BD_VISUAL_SELECTION_HIDDEN "\xee\xae\x87"       // U+eb87
#define ICON_BD_VISUAL_SELECTION_SELECTABLE "\xee\xae\x88"   // U+eb88
#define ICON_BD_VISUAL_SELECTION_UNSELECTABLE "\xee\xae\x89" // U+eb89
#define ICON_BD_VOLUME_DATA "\xee\xae\x8a"                   // U+eb8a
#define ICON_BD_VPAINT_HLT "\xee\xae\x8b"                    // U+eb8b
#define ICON_BD_WINDOW "\xee\xae\x8c"                        // U+eb8c
#define ICON_BD_WORDWRAP_OFF "\xee\xae\x8d"                  // U+eb8d
#define ICON_BD_WORDWRAP_ON "\xee\xae\x8e"                   // U+eb8e
#define ICON_BD_WORKSPACE "\xee\xae\x8f"                     // U+eb8f
#define ICON_BD_WORLD "\xee\xae\x90"                         // U+eb90
#define ICON_BD_WORLD_DATA "\xee\xae\x91"                    // U+eb91
#define ICON_BD_WPAINT_HLT "\xee\xae\x92"                    // U+eb92
#define ICON_BD_X "\xee\xae\x93"                             // U+eb93
#define ICON_BD_X_RAY "\xee\xae\x94"                         // U+eb94
#define ICON_BD_ZOOM_ALL "\xee\xae\x95"                      // U+eb95
#define ICON_BD_ZOOM_IN "\xee\xae\x96"                       // U+eb96
#define ICON_BD_ZOOM_OUT "\xee\xae\x97"                      // U+eb97
#define ICON_BD_ZOOM_PREVIOUS "\xee\xae\x98"                 // U+eb98
#define ICON_BD_ZOOM_SELECTED "\xee\xae\x99"                 // U+eb99
